"""initial schema

Revision ID: 4f1dd4d76894
Revises: 
Create Date: 2026-06-22 22:40:28.111525
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f1dd4d76894'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('ipi', sa.String(length=11), nullable=True),
    sa.Column('role', sa.Enum('writer', 'publisher', 'performer', 'label', 'distributor', name='party_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_ipi'), 'parties', ['ipi'], unique=False)
    op.create_table('rate_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('royalty_type', sa.Enum('mechanical', 'performance', 'digital_performance', name='royalty_type'), nullable=False),
    sa.Column('registry', sa.Enum('mlc', 'ascap', 'bmi', 'sesac', 'soundexchange', name='registry_name'), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('royalty_type', 'registry', 'version', 'effective_date', name='rate_card_version_unique')
    )
    op.create_table('raw_registry_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registry', sa.Enum('mlc', 'ascap', 'bmi', 'sesac', 'soundexchange', name='registry_name'), nullable=False),
    sa.Column('request_url', sa.Text(), nullable=True),
    sa.Column('request_params', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_registry_responses_content_hash'), 'raw_registry_responses', ['content_hash'], unique=False)
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('iswc', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iswc')
    )
    op.create_table('recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('artist_name', sa.String(length=512), nullable=True),
    sa.Column('isrc', sa.String(length=12), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('spotify_id', sa.String(length=64), nullable=True),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordings_isrc'), 'recordings', ['isrc'], unique=False)
    op.create_table('registration_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.Column('registry', sa.Enum('mlc', 'ascap', 'bmi', 'sesac', 'soundexchange', name='registry_name'), nullable=False),
    sa.Column('side', sa.Enum('master', 'composition', name='copyright_side'), nullable=False),
    sa.Column('status', sa.Enum('registered', 'not_found', 'ambiguous', 'unresolved', 'error', name='registration_status'), nullable=False),
    sa.Column('confidence_band', sa.Enum('high', 'medium', 'low', name='confidence_band'), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('matched_identifier', sa.String(length=64), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw_response_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(work_id IS NOT NULL) <> (recording_id IS NOT NULL)', name='regcheck_exactly_one_target'),
    sa.ForeignKeyConstraint(['raw_response_id'], ['raw_registry_responses.id'], ),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('role', sa.Enum('writer', 'publisher', 'performer', 'label', 'distributor', name='party_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(work_id IS NOT NULL) <> (recording_id IS NOT NULL)', name='split_exactly_one_parent'),
    sa.CheckConstraint('percent >= 0 AND percent <= 100', name='split_percent_range'),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('splits')
    op.drop_table('registration_checks')
    op.drop_index(op.f('ix_recordings_isrc'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_table('works')
    op.drop_index(op.f('ix_raw_registry_responses_content_hash'), table_name='raw_registry_responses')
    op.drop_table('raw_registry_responses')
    op.drop_table('rate_cards')
    op.drop_index(op.f('ix_parties_ipi'), table_name='parties')
    op.drop_table('parties')
    # ### end Alembic commands ###
    # Autogenerate drops tables but NOT the Postgres ENUM types — drop them explicitly so
    # `downgrade base` leaves a clean DB (otherwise a re-`upgrade` collides on CREATE TYPE).
    for enum_name in (
        "party_role",
        "royalty_type",
        "registry_name",
        "registration_status",
        "confidence_band",
        "copyright_side",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
